### ISSUE TITLE
no kind "EtcdCluster" is registered for version "etcd.database.coreos.com/v1beta2"

### ISSUE THREAD

**Issue by ArrH** [coreos/etcd-operator#1391]
Upon the attempt to create example-etcd-cluster.yaml, using Kubernetes UI, I get the following error:
`unable to decode "example-etcd-cluster.yaml": no kind "EtcdCluster" is registered for version "etcd.database.coreos.com/v1beta2"`

Is this an issue or am I missing something in the documentation?

**Comment by hongchaodeng** [comment]
You need to start etcd operator first.
Can you give detailed steps how you encounter this problem?

**Comment by ArrH** [comment]
Yeah, so first I created the deployment using the deployment.yaml: 

`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.5.1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
`
This step was completed without any issues. And then I tried to create example-etcd-cluster.yaml. Upon execution of command, I received the error as in the description of the issue

**Comment by ArrH** [comment]
I've tried playing around with the solutions to similar problems people had and reported here, but so far no luck.

**Comment by ArrH** [comment]
UPDATE:

Alright, I tried experimenting more. I thought my K8 RBAC my be the issue (even though my K8 version is 1.6.7  thus lower than 1.7 and according to docs this should not be the case). I've tried creating the following .yaml file:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
```
But this gave the similar error as described in the issue:
`unable to decode "rbac1.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"`

No idea what going wrong here. My Kubernetes is running on AWS. It was build using the following image: [kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-28].

Any help is really appreciated.

**Comment by xiang90** [comment]
can you get the logging from etcd operator?

**Comment by ArrH** [comment]
Every 30 seconds it says that
`the server could not find the requested resource" pkg=controller`

**Comment by xiang90** [comment]
@ArrH Can you provide the full logging lines from etcd operator? Not just one line?

**Comment by ArrH** [comment]
Yeah. I just updated my K8 to v1.7.2. Here are the logs:

```
2017-09-14T14:34:23.158916042Z time="2017-09-14T14:34:23Z" level=info msg="etcd-operator Version: 0.5.2" 
2017-09-14T14:34:23.158965525Z time="2017-09-14T14:34:23Z" level=info msg="Git SHA: 0fa2f7d" 
2017-09-14T14:34:23.158986632Z time="2017-09-14T14:34:23Z" level=info msg="Go Version: go1.8.1" 
2017-09-14T14:34:23.158993271Z time="2017-09-14T14:34:23Z" level=info msg="Go OS/Arch: linux/amd64" 
2017-09-14T14:35:09.972748678Z time="2017-09-14T14:35:09Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"etcd-operator", UID:"a096b050-9705-11e7-8be4-02db6d978ae7", APIVersion:"v1", ResourceVersion:"26888990", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd-operator-1838408530-jhj2r became leader"
```

Not getting the package issue anymore.

**Comment by hongchaodeng** [comment]
Closing since it is solved.
Thanks for reporting and collaboration.

**Comment by henry-zhang** [comment]
I also have this issue

**Comment by soderluk** [comment]
So, just to ask an obvious question, how was this solved? By updating K8? 
I have the version 1.11.2 and this is still an issue. I get `error: unable to recognize "etcd.yaml": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2""`. Any ideas for a solution here?
I used the etcd-operator, and it worked correctly, but after applying the cluster yaml from https://github.com/coreos/etcd-operator/blob/master/example/example-etcd-cluster.yaml it fails with the above error.

**Comment by rigazilla** [comment]
Hi, same problem here

**Comment by roys8** [comment]
This issue is resolved.
The issue was related to `apiVersion: "etcd.database.coreos.com/v1beta2"`

To solve this, you should be able to get the output by running
`kubectl get customresourcedefinitions`

and get output as ```etcdbackups.etcd.database.coreos.com 
etcdclusters.etcd.database.coreos.com
etcdrestores.etcd.database.coreos.com```

Otherwise, the rbac directory have `create_role.sh`

**Comment by chungktran** [comment]
I've ran into this same issue and the problem was the order of applying the operator and CRD. You need to apply the CRD first then the operator.

If you're using the vault-operator you must apply the etcd CRD before applying the vault operator yaml file.

**Comment by smilelikeshit** [comment]
@roys8 thank solved my issue
